spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=CTT
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    publisher-confirms: true
    publisher-returns: true
  resources:
    static-locations: classpath:/static/,classpath:/view/,classpath:/public,classpath:/resources/

#    pagehelper.helper-dialect=mysql
#    pagehelper.params=count=countSql
#    pagehelper.reasonable=true
#    pagehelper.support-methods-arguments=true
pagehelper:
  helper-dialect: mysql
  params: params=count=countSql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml


