spring:
  datasource:
    url: jdbc:mysql://10.222.10.59:3306/sys?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    suffix: .html
    check-template-location: true
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    mode: LEGACYHTML5


#    pagehelper.helper-dialect=mysql
#    pagehelper.params=count=countSql
#    pagehelper.reasonable=true
#    pagehelper.support-methods-arguments=true
pagehelper:
  helper-dialect: mysql
  params: params=count=countSql
  reasonable: true
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml


